### ISSUE TITLE
FileNotFoundError when trying to do anything

### ISSUE THREAD

**Issue by Decapitater** [cow-killer/dualsense-led-configurator#4]
hi , software is non functional getting errors based on /sys/devices/pci0000:00/0000:00:08.1/0000:28:00.3/usb5/5-4/5-4:1.0/bluetooth/hci0/hci0:256/0005:054C:0CE6.000C/leds/input:white:player-1/brightness or any other @cow-killer

**Comment by the-outcaster** [comment]
Are you running the script as root?

**Comment by Decapitater** [comment]
yes

**Comment by the-outcaster** [comment]
Can you send me the text that you get from the terminal when trying to run the application?

**Comment by Decapitater** [comment]
sure

**Comment by Decapitater** [comment]
Its just like this for every options (this one is for LED2 toggle)

```
Traceback (most recent call last):
  File "~/dualsense-led-configurator/ds_led.py", line 418, in led_clicked
    self.toggle_individual_led(data[0])
  File "~/dualsense-led-configurator/ds_led.py", line 232, in toggle_individual_led
    wr = open(
FileNotFoundError: [Errno 2] No such file or directory: '/sys/devices/pci0000:00/0000:00:08.1/0000:28:00.3/usb5/5-4/5-4:1.0/bluetooth/hci0/hci0:256/0005:054C:0CE6.000C/leds/input:white:player-2/brightness'
```

**Comment by Decapitater** [comment]
@linuxgamingcentral what is wrong ?

**Comment by the-outcaster** [comment]
Is that just for LED 2 or does that apply to any of the buttons you click?

**Comment by Decapitater** [comment]
any

**Comment by Decapitater** [comment]
maybe folder names are hardcoded ?

**Comment by Decapitater** [comment]
@cow-killer  ? , @linuxgamingcentral  anything ?

**Comment by ivanbratovic** [comment]
@Decapitater, can you please test with the latest code? I believe I had this same error once, but it no longer appears after PR #5.
